### ISSUE TITLE
`--personal-access-token` is required even when passing configuration file

### ISSUE THREAD

**Issue by tsimbalar** [robertohuertasm/figma-asset-downloader#11]
### Steps to reproduce
If I run fad like this : 

```
fad -c "path/to/fad.toml" -f "xxx" -d "yyy:zzz" -p "assets/figma-images" -e svg -s 1
```

and my `fad.toml` looks like this : 

```toml
personal_access_token = "top-secret-token"
```

### Actual behavior

`fad` errors with : 

```
error: The following required arguments were not provided:
    --personal-access-token <personal-access-token>

USAGE:
    fad --config-path <config-path> --document-id <document-id> --file-extensions <file-extensions>... --file-id <file-id> --file-scales <file-scales>... --path <path> --personal-access-token <personal-access-token>
```

### Expected
`fad` should take the token from my configuration file if it is not provided through the CLI. 

(i.e. my understanding is that we take values from the config file, and whatever is provided through CLI arguments overrides it)

### Context
with `fad v0.7.3` (i.e. the latest as of now) on macOS.

**Comment by robertohuertasm** [comment]
I'll take a look, but note that in the documentation states: `-t, -f, -d` are always mandatory if at least any one of them is manually provided.

I think we can remove this restriction and leave it as you suggested. I'll prepare a PR for this.

**Comment by tsimbalar** [comment]
@robertohuertasm 

> I'll take a look, but note that in the documentation states: -t, -f, -d are always mandatory if at least any one of them is manually provided.

I did look for this information in the documentation, but I couldn't find it U_U
