### ISSUE TITLE
`The provided configuration file was not found!` when not passing `-c` flag

### ISSUE THREAD

**Issue by tsimbalar** [robertohuertasm/figma-asset-downloader#6]
If I launch `fad` with something like 

```
fad -t <MY_PAT> -f <some_id> -d <another_id> -p downloaded -s 1 -e svg
```

It fails with : 

```
⛔   The provided configuration file was not found!
Error: No such file or directory (os error 2)
```

### Expected outcome
It should just take into account the command line arguments and not look for a configuration file at all.

### Context 

Version `0.7.2` on macOS

### Workaround
Current workaround is to create an empty `fad.toml` file with

```
touch fad.toml
```

**Comment by robertohuertasm** [comment]
Good point! At the moment the config file is mandatory but I agree it makes no sense. The fix should be pretty straightforward. Thanks for pointing this out!
